python -m multi_intent_classification.services.train \
    --dataloader_workers 2 \
    --device cuda \
    --seed 42 \
    --epochs 10 \
    --learning_rate 3e-5 \
    --weight_decay 0.01 \
    --warmup_steps 50 \
    --max_length 256 \
    --pad_mask_id -100 \
    --model vinai/phobert-base-v2 \
    --train_batch_size 16 \
    --valid_batch_size 8 \
    --test_batch_size 8 \
    --train_file multi_intent_classification/dataset/train.json \
    --valid_file multi_intent_classification/dataset/val.json \
    --test_file multi_intent_classification/dataset/test.json \
    --output_dir ./multi_intent_classification/models/classification \
    --record_output_file multi_intent_classification/output.json \
    --evaluate_on_accuracy True \

